
filter:
  exclude: "defaults/exclude.txt"
  min_length:
    Orthohantavirus_andesense:
      l: 200
      m: 200
      s: 100
    Orthohantavirus_hantanense:
      l: 300
      m: 200
      s: 260
    Orthohantavirus_puumalaense:
      l: 200
      m: 150
      s: 150
    Orthohantavirus_seoulense:
      l: 200
      m: 150
      s: 250
    Orthohantavirus_tulaense:
      l: 450
      m: 200
      s: 200
  max_length:
    Orthohantavirus_andesense:
      l: 7000
      m: 4000
      s: 2000
    Orthohantavirus_hantanense:
      l: 7000
      m: 4000
      s: 2000
    Orthohantavirus_puumalaense:
      l: 7000
      m: 4000
      s: 2000
    Orthohantavirus_seoulense:
      l: 7000
      m: 4000
      s: 2000
    Orthohantavirus_tulaense:
      l: 7000
      m: 4000
      s: 2000
  
strain_id_field: "accession"

tree:
  method: "iqtree"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_rate: 0.0014
  root: "mid_point"

ancestral:
  inference: "joint"

traits:
  columns: "country"

export:
  auspice_config: "defaults/auspice_config.json"
  description: "defaults/description.md"
  segment_metadata_columns:
    - accession_version
    - length
    - date_released
    - date_updated